public abstract class Password 
{
	private char[] pass; //stores the password generated by the generatePass() method. 
	//it is private, and there should be NO get() method in order to protect it. 
	//All comparisons done within this class.

	public Password()
	{
		pass = generatePass(); //this will tell the compiler to look for a implementation in some subclass
	}
  
	public abstract char[] generatePass(); //each subclass should override this
	public abstract boolean guess(); //each subclass should override this
	
	public char[] compare(char[] pass2) //returns a char[] of the password with - where there is a wrong guess and the correct output for a right guess
	{
		char[] wrongPlaces = new char[pass.length];
		for(int i = 0; i<pass.length; i++) 
		{
			if(pass[i] != pass2[i])
				wrongPlaces[i] = '-';
			else
				wrongPlaces[i] = pass[i];
		}
		return wrongPlaces;
	}
}
